{
 "title": "Radix Validator Node Alerts v1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current State Difference",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_counters_sync_target_current_diff"
    }
   ]
  },
  {
   "title": "Current Epoch Missed Proposals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_counters_radix_engine_cur_epoch_missed_proposals"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_epochmanager_currentview_epoch"
    }
   ]
  },
  {
   "title": "Epoch Proposals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_counters_radix_engine_cur_epoch_completed_proposals"
    }
   ]
  },
  {
   "title": "Proposals per Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(info_counters_bft_proposals_made[60m])"
    }
   ]
  },
  {
   "title": "Total Proposals Made",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_counters_bft_proposals_made"
    }
   ]
  },
  {
   "title": "Timed Out Views",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_counters_bft_timed_out_views"
    }
   ]
  },
  {
   "title": "Sync Request Timeouts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_counters_bft_sync_request_timeouts"
    }
   ]
  },
  {
   "title": "Missed Proposal Alert - 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "info_counters_radix_engine_cur_epoch_missed_proposals"
    }
   ]
  },
  {
   "title": "Missed Proposals Alert - >1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "info_counters_radix_engine_cur_epoch_missed_proposals"
    }
   ]
  },
  {
   "title": "Node Status Alert",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 16 },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}