{
 "title": "Radix Dashboard 1.0.7 v2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Versions / Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_sync_target_state_version[1m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (info_counters_sync_target_current_diff / info_counters_sync_target_state_version)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "info_counters_time_duration" }
   ]
  },
  {
   "title": "% Synced",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (info_counters_sync_target_current_diff / info_counters_sync_target_state_version)) * 100"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nodeinfo", "legendFormat": "{{ branch_and_commit }}" }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "View In Epoch",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_epochmanager_currentview_view",
     "legendFormat": "View"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_epochmanager_currentview_epoch"
    }
   ]
  },
  {
   "title": "Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nodeinfo", "legendFormat": "{{ owner_address }}" }
   ]
  },
  {
   "title": "Registered Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodeinfo{validator_registered=\"true\"}"
    }
   ]
  },
  {
   "title": "Validator Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nodeinfo", "legendFormat": "{{ own_validator_address }}" }
   ]
  },
  {
   "title": "Node Key",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodeinfo", "legendFormat": "{{ key }}" }
   ]
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodeinfo{is_in_validator_set=\"true\"}"
    }
   ]
  },
  {
   "title": "XRD Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "balance_xrd" }
   ]
  },
  {
   "title": "XRD Staked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "validator_total_stake" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "info_counters_mempool_count" }
   ]
  },
  {
   "title": "Mempool Additions / Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_mempool_add_success{}[$__rate_interval])"
    }
   ]
  },
  { "title": "Radix Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Network Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_peers" }
   ]
  },
  {
   "title": "Network Peers Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "total_peers", "legendFormat": "Peers" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "total_validators" }
   ]
  },
  {
   "title": "Network Validators Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "total_validators", "legendFormat": "Validators" }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "processcpuload", "legendFormat": "Process CPU Load" },
    { "expr": "systemcpuload", "legendFormat": "System CPU Load" }
   ]
  },
  {
   "title": "Heap Memory Usage Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "heapmemoryusage_max", "legendFormat": "Maximum Heap Size" },
    { "expr": "heapmemoryusage_used", "legendFormat": "Used Heap Size" }
   ]
  },
  {
   "title": "Heap Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(heapmemoryusage_used / heapmemoryusage_max) * 100"
    },
    { "legendFormat": "max" }
   ]
  }
 ]
}